### ISSUE TITLE
Fix indel calling

### ISSUE THREAD

**Issue by samlhao** [czbiohub/sc2-illumina-pipeline#56]
The indel calling doesn't work right now, so the combined stats end up not showing the correct count.

**Comment by jackkamm** [comment]
Closing as stale/lack of details...possibly should investigate and reopen a new issue

Anecdotally, our consensus genomes definitely have indels, and I do believe they end up in our VCFs, but I'm not sure whether they correctly wind up in the CSV table of genome stats...this may have also changed over time.
