### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by batson** [czbiohub/sc2-illumina-pipeline#78]
MIT, Apache, or GPL3 may be appropriate, depending on the team's intentions for community reuse.

**Comment by batson** [comment]
If the repo still has code from the [https://github.com/connor-lab/ncov2019-artic-nf](https://github.com/connor-lab/ncov2019-artic-nf) then it may necessarily be AGPL3.0 via copyleft.

**Comment by jackkamm** [comment]
I added AGPL. This is not strictly necessary, we never directly used code from ncov2019-artic-nf (that is nextflow v2, whereas our pipeline is nextflow v1), and it looks like they only added their license in October. So we can always change the license later if we want. However, I like AGPL fine, so am using it by default.
